export const projects = [
  {
    name: "Holidaze",
    description: "Holidaze is a modern accommodation booking application.",
    audience: "Designed for the general public",
    design: ["Simplistic", "Clear"],
    techStack: ["React", "TypeScript", "Tailwind CSS", "HTML"],
    logo: "/Holidaze-logo.svg",
    favicon: "/holidaze-favicon.svg",
    mockup: "/holidaze-mockup.svg",
  },
  {
    name: "TimeLess",
    description: "A futuristic AI-driven trading platform.",
    audience: "Designed for traders and investors.",
    design: ["Innovative", "User-friendly"],
    techStack: ["React", "TypeScript", "Tailwind CSS"],
    logo: "/timelesslogo.png",
    favicon: "/timeless-favicon.png",
    mockup: "/Timeless-mobile.svg",
  },
  {
    name: "Holidaze",
    description: "Holidaze is a modern accommodation booking application.",
    audience: "Designed for the general public",
    design: ["Simplistic", "Clear"],
    techStack: ["React", "TypeScript", "Tailwind CSS", "HTML"],
    logo: "/Holidaze-logo.svg",
    favicon: "/holidaze-favicon.svg",
    mockup: "/vindt-mobile-mockup.svg",
  },
  {
    name: "Holidaze",
    description: "Holidaze is a modern accommodation booking application.",
    audience: "Designed for the general public",
    design: ["Simplistic", "Clear"],
    techStack: ["React", "TypeScript", "Tailwind CSS", "HTML"],
    logo: "/Holidaze-logo.svg",
    favicon: "/holidaze-favicon.svg",
    mockup: "/Holidaze-mockup-laptop.png",
  },
];
